#!/usr/bin/env bash
# Install nginx
sudo apt-get update && sudo apt-get install nginx -y

sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html

sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
