#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install haproxy=2.4.\* -y
sudo apt update && sudo apt upgrade -y

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

config=\
"
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
backend myservers
	balance roundrobin
	server 2171-web-01 34.139.86.175:80 check
	server 2171-web-02 3.239.7.133:80 check
frontend myfrontend
	bind :80
	mode http
	default_backend myservers
"

echo "$config" > /etc/haproxy/haproxy.cfg

sudo service haproxy restart
