#!/usr/bin/env bash
# Script that configures an Ubuntu server with:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
